### PR TITLE
Add verification of BLS short signatures

### PR DESCRIPTION
**Pull request by randombit**
Hi!

I work on a system that uses BLS with short signatures (ie signatures in G1 and public keys in G2). We'd like to be able to use this library to verify such signatures.

Does my current change seem like the general direction of something you would accept? If so I will add also aggregation support, and of course tests. (And also if you want, keygen and signature generation - I don't think we need those but if you want them for parity that certainly is understandable.)

If the approach I'm taking here is not what you would want, just let me know what you're looking for and I'll do that instead!

Related - #64

### CODE REVIEW

**Comment by paulmillr** [comment]
Yes, that should work. Keygen and sig gen would also be great!

**Comment by randombit** [comment]
This is ready for review

**Comment by paulmillr** [comment]
thanks

**Comment by paulmillr** [comment]
@randombit could you also update README docs, please?

**Comment by randombit** [comment]
@paulmillr Sure, I will open another PR on Monday. Thanks for the fast merge!

**Pull request merged**
