### PR TITLE
Allow numberToBytes to take a number

### PR DESCRIPTION
**Pull request by madeken**

### CODE REVIEW

**Comment by paulmillr** [comment]
Is that actually useful to you?

**Comment by madeken** [comment]
lol, slightly. Right now I have: `numberToVarBytesBE(BigInt(nonce))` which isn't a big deal. But seems kinda pointless to convert to a BigInt just to satisfy the type-checker, when `numberToHexUnpadded` already supports `number` 👯‍♀️

**Comment by paulmillr** [comment]
tests seem to fail

**Comment by paulmillr** [comment]
added by myself

**Pull request closed without merging**
