### PR TITLE
fix: check extraEntropy according to the spec

### PR DESCRIPTION
**Pull request by mahnunchik**
#55

### CODE REVIEW

**Comment by paulmillr** [comment]
Length of Fp.bytes are for compatibility with libsecp256k1: https://github.com/bitcoin-core/secp256k1/blob/67214f5f7d8e0bdf193ceb1f47ba8277d1a0871a/src/secp256k1.c#L476

Do you need longer value for something, or this is just fixing spec non-compliance?

**Comment by mahnunchik** [comment]
I'm moving from our lovely `elliptic` module... 

For the EOS crypto 1 byte additional data is used. So I checked the spec and realized that it is not mandatory for additional data to be 32 bytes.

According to the comment from libsecp256k1 https://github.com/bitcoin-core/secp256k1/blob/67214f5f7d8e0bdf193ceb1f47ba8277d1a0871a/src/secp256k1.c#L477 additional 16 bytes may be appended too.

**Comment by paulmillr** [comment]
>For the EOS crypto 1 byte additional data is used. So I checked the spec and realized that it is not mandatory for additional data to be 32 bytes.

if the byte is e.g. `de`, you can do this: `0000000000000000000000000000000000000000000000000000000000000000de`. Does this work?

With regards to 16-byte algorithm name: that's true.

**Comment by mahnunchik** [comment]
Yes, it is possible to produce valid EOS signature by using `00000000000000000000000000000000000000000000000000000000000000de` but not the same signature as original EOS code produces.

I think it is better to follow specification and check that `extraEntropy` is bytes but not check the size.

**Comment by paulmillr** [comment]
I agree with you.

> but not the same signature as original EOS code produces

That's weird. I would have thought they are the same - which would have worked for now.

**Comment by paulmillr** [comment]
Could you add a test for this, please?

**Comment by paulmillr** [comment]
@mahnunchik ping

**Comment by mahnunchik** [comment]
@paulmillr done

**Comment by mahnunchik** [comment]
Yep, additional test may be added just to test different entropy sizes.

**Comment by paulmillr** [comment]
Ok, please add it and revert json change and we'll be good to go.

**Comment by mahnunchik** [comment]
@paulmillr please check the changes

**Pull request merged**
